name: weather_repository
description: Repository for weather information.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.0-prev3
  equatable: ^2.0.0

dev_dependencies:
  mocktail: 0.1.1
  very_good_analysis: ^2.0.0
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8